version: "3.8"

services:
  mysqldb:
    image: mysql:8
    container_name: mysqldb
    restart: unless-stopped
    env_file: ./.env
    environment:
      - MYSQL_ROOT_PASSWORD=$MYSQLDB_ROOT_PASSWORD
      - MYSQL_USER=$MYSQLDB_USER
      - MYSQL_PASSWORD=$MYSQLDB_PASSWORD
      - MYSQL_DATABASE=$MYSQLDB_DATABASE
    ports:
      - "3307:3306"
  app:
    image: task:latest
    depends_on:
      - mysqldb
    build: ./
    restart: unless-stopped
    env_file: ./.env
    environment:
      - SPRING.DATASOURCE.URL=jdbc:mysql://mysqldb:$MYSQLDB_DOCKER_PORT/$MYSQLDB_DATABASE
      - SPRING.DATASOURCE.USERNAME=$MYSQLDB_USER
      - SPRING.DATASOURCE.PASSWORD=$MYSQLDB_PASSWORD
    ports:
      - "8081:8080"
    stdin_open: true
    tty: true